---
version: "2"
plugins:
  eslint:
    enabled: true
    channel: "eslint-7"
  duplication:
    enabled: true
    config:
      languages:
        - javascript
checks:
  file-lines:
    enabled: false
exclude_patterns:
  - doc/
  - node_modules/
  - release/
  - scripts/
  - test/
  - index.js
  - webpack.config.js
